name: vagrant validate

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install vagrant
        run: sudo apt-get install -y vagrant
      
      - run: vagrant validate
