name: vagrant validate

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: vagrant
          version: 1.0

      - name: Install vagrant
        run: sudo apt-get install -y vagrant

      - run: vagrant validate
